# Generated by Django 3.1 on 2021-10-27 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_valu',
            new_name='variation_value',
        ),
    ]
